theme: minima
title: EVM Golf
github_username: evm-golf
header_pages:
  - challenges/README.md
  - leaderboard/index.md
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
